# Notebook 4: Algorismes per text


<div class="alert alert-error">
<p><strong><center>Aquesta pràctica és avaluable</center></strong></p>
<p>L'has de lliurar amb UN ÚNIC FITXER (Notebook4.ipynb),amb el  Notebook COMPLETAT AMB EL CONJUNT DE FUNCIONS QUE S’HAN D'IMPLEMENTAR a les cel·les que s'indica, i l'execució dels tests inclosos en l'enunciat.</p>  
<p>ATENCIÓ: No es poden usar funcions de Python implementades en llibreries externes que resolguin el *quid* de l'exercici.</p>

## Exercici 1 (3 punts)

Donades dues cadenes de caràcters identificar la longitud de la subseqüència compartida més llarga. Una subseqüència és una seqüència de caràcters en el mateix ordre que a la cadena original però no necessàriament consecutius.</p>

Per exemple de la paraula ACBA, podem treure'n les subseqüències AC,AB,AA, ACB, ACA, ACBA, CB, CA, CBA, BA

**Pregunta 1**: Proposa algunes parelles de cadenes i digues quina és la subseqüència comú més llarga

Indica aquí les teves respostes

In [1]:
def subSComu(cadena1, cadena2):
    
    """El que fa la funció les a partir de dos strings, retornar la longitud de la subseqüència més llarga comú entre els dos 
    :param els dos strings, cadena1 i cadena2, en aquest cas
    :return la longitud en forma de nombre de la subSeq comú més llarga
    """
    
    if len(cadena1)==0 or len(cadena2)==0:
        return 0
    
    sbcd11=cadena1[0]
    sbcd12= cadena1[1:]
    
    sbcd21= cadena2[0]
    sbcd22=cadena2[1:]
    
    if sbcd11==sbcd21:
        return (1+subSComu(sbcd12,sbcd22))
        
    else:
        longSubSequencia= max(subSComu(cadena1, sbcd22),subSComu(sbcd12,cadena2))
        
    return longSubSequencia

In [2]:
# Test de la funció
subSComu('SUBCADENA','ABECEDARI')

4

## Exercici 2 (3 punts)

També podem construir la solució amb una taula que va guardant els valors de la subseqüència comú més llarga:


|   |   | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 |
|---|---|---|---|---|---|---|---|---|---|---|
|---|---| S | U | B | C | A | D | E | N | A |
| 0 | A | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| 1 | B | 0 | 0 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |
| 2 | E | 0 | 0 | 1 | 1 | 1 | 1 | 2 | 2 | 2 |
| 3 | C | 0 | 0 | 1 | 2 | 2 | 2 | 2 | 2 | 2 |
| 4 | E | 0 | 0 | 1 | 2 | 2 | 2 | 3 | 3 | 3 |
| 5 | D | 0 | 0 | 1 | 2 | 2 | 3 | 3 | 3 | 3 |
| 6 | A | 0 | 0 | 1 | 2 | 3 | 3 | 3 | 3 | 4 |
| 7 | R | 0 | 0 | 1 | 2 | 3 | 3 | 3 | 3 | 4 |
| 8 | I | 0 | 0 | 1 | 2 | 3 | 3 | 3 | 3 | 4 |


La casella[i][j] guarda el valor de longitud de la subseqüència més llarga entre cadena1[0:j] i cadena2[0:i]

Per ex. la casella[2][6] guarda la longitud de la subseqüència més llarga entre cadena1[0:6] i cadena2[0:2]. Efectivament 2 és la longitud de la subseqüència més llarga entre "SUBCADE" i "ABE", que es correspon a "AE"


Crea doncs una nova funció subSComuTaula que generi aquesta taula i que retorni el resultat en base a la taula.

In [30]:
import numpy as np

def subSComuTaula(cadena1, cadena2):
    """
    A partir de dues cadenes de caràcters, obtindrem les subseqüències comuns més llargues.
    :param les dues cadenes
    :return la taula i la la subSeq mes llarga
    """
    
   
    n=len(cadena1)+1    #Cadena1
    m=len(cadena2)+1    #Cadena2  
    
    taulaSolucions=np.zeros((n,m))
    
    if cadena1==0 or cadena2==0:
        longSubSequencia=0
        
    #sumar 1+x(diagonal) si es igual
    #escollir entre max esquerra i adalt
    
    for i in range(1,n):
        for j in range(1,m):
            if cadena1[i-1]==cadena2[j-1]:
                taulaSolucions[i][j]=taulaSolucions[i-1][j-1]+1
            else:
                taulaSolucions[i][j]=max(taulaSolucions[i-1][j],taulaSolucions[i][j-1])
        
    longSubSequencia=taulaSolucions[n-1][m-1]
        
    print(taulaSolucions)
    return (int(longSubSequencia))

In [31]:
subSComuTaula('ABECEDARI', 'SUBCADENA')

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  1.  1.  1.  1.]
 [ 0.  0.  0.  1.  1.  1.  1.  1.  1.  1.]
 [ 0.  0.  0.  1.  1.  1.  1.  2.  2.  2.]
 [ 0.  0.  0.  1.  2.  2.  2.  2.  2.  2.]
 [ 0.  0.  0.  1.  2.  2.  2.  3.  3.  3.]
 [ 0.  0.  0.  1.  2.  2.  3.  3.  3.  3.]
 [ 0.  0.  0.  1.  2.  3.  3.  3.  3.  4.]
 [ 0.  0.  0.  1.  2.  3.  3.  3.  3.  4.]
 [ 0.  0.  0.  1.  2.  3.  3.  3.  3.  4.]]


4

# Exercici 3 (4 punts)

Proposar una solució al mateix exercici, basant-te en els resultats de la taula anterior, que optimitzi l'espai que ocupa la solució, és a dir, guardant només aquells valors imprescindibles per a la solució.

In [44]:
import numpy as np

def subSComuOpt(cadena1, cadena2):
    """
    Enlloc d'obtindre tota la taula, només obtindrem la part que ens retorna la solució
    :param les dues cadenes
    :return el nombre més rellevant de la taula anterior
    """
    
    n=len(cadena1)+1    
    m=len(cadena2)+1
    taulaSolucions=np.zeros((n,m))

    for i in range(1,n):
        for j in range(1,m):
            if cadena1[i-1]==cadena2[j-1]:
                taulaSolucions[1][j]=taulaSolucions[0][j-1]+1
            else:
                taulaSolucions[1][j]=max(taulaSolucions[0][j],taulaSolucions[1][j-1])
            for z in range(m):
                taulaSolucions[0][j]=taulaSolucions[1][j]
                longSubSequencia=taulaSolucions[1][m-1]
    
    
    
    
    return (int(longSubSequencia))

In [45]:
subSComuOpt("ABECEDARI","SUBCADENA")

4